### ISSUE TITLE
Signup Function Broken

### ISSUE THREAD

**Issue by paperpatch** [paperpatch/trackend#29]
The signup button currently does not work due to new incorporated data.

- Need to add email post routing (as it only takes in name and password).
- Refer to the module Just Tech News <-- can be similar to this
- Incorporate the 'confirm password' section. Signup does not go through if passwords do not match.

**Comment by davezer** [comment]
Fixed the bug with the signup form. Now works as intended. 
Quick note - I had to add "defaultValue: 2" (this value can be changed to whatever the default user will be) to the role_id to get it to work, as it wouldn't save the new user without adding a role_id to it. Without setting it to a default value it was returning as null and making it not work.
